import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/components/CustomCursor";

const dmSans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="" style={{ cursor: "none", scrollBehavior: "smooth" }}>
      <body className={`${dmSans.variable} font-sans antialiased`} style={{ cursor: "none" }}>
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
